"""
Sample 10-K narrative text, split by page, standing in for what
rag.chunker would extract from a real filing PDF via pdfplumber.

This text is written by the project author to be representative of the
kinds of statements a warehouse-club retailer's 10-K risk factors and
business sections contain -- it is illustrative for demo purposes, not a
verbatim copy of any actual Costco filing, and should not be cited as
Costco's actual disclosed language in a real memo. For a real memo, run
edgar_client.fetch_filing_document_url() and chunker.chunk_pdf() on the
live filing.
"""

SAMPLE_PAGES = [
    # Page 1 -- Business overview
    (
        "Item 1. Business\n\n"
        "The Company operates a chain of membership warehouses under the "
        "Costco Wholesale name, offering low prices on a limited selection "
        "of nationally branded and private-label products across a wide "
        "range of merchandise categories. As of the most recent fiscal "
        "year end, the Company operated warehouses across multiple "
        "countries, with membership fee income representing a significant "
        "and growing contributor to operating profit.\n\n"
        "The Company's business model relies on high sales volume and "
        "rapid inventory turnover generated by offering members low prices "
        "on a limited number of items in a wide range of categories."
    ),
    # Page 2 -- more business overview
    (
        "The Company's membership renewal rate has historically remained "
        "high, and management views membership fee income as a key "
        "indicator of member loyalty and satisfaction with the shopping "
        "experience. E-commerce operations, while a smaller portion of "
        "total revenue than warehouse sales, have grown as the Company "
        "has expanded fulfillment capabilities."
    ),
    # Page 3 -- Risk Factors begins
    (
        "Item 1A. Risk Factors\n\n"
        "Our business is subject to numerous risks and uncertainties, "
        "including those described below. The following risks could "
        "materially and adversely affect our business, financial "
        "condition, and results of operations.\n\n"
        "Competition. We operate in a highly competitive environment "
        "against other warehouse clubs, big box retailers, e-commerce "
        "companies, and grocery chains, many of which compete aggressively "
        "on price. Increased price competition could compress our margins "
        "and adversely affect our operating results."
    ),
    # Page 4 -- more risk factors
    (
        "Supply Chain and Inventory Risk. We depend on our ability to "
        "source merchandise at acceptable prices and to maintain efficient "
        "distribution and inventory management systems. Disruptions to "
        "global supply chains, including port congestion, shipping cost "
        "volatility, and supplier concentration, could impair our ability "
        "to maintain in-stock positions on key merchandise and increase "
        "our cost of goods sold."
    ),
    # Page 5 -- more risk factors
    (
        "Labor Costs and Availability. Our operating model depends on a "
        "large hourly workforce. Increases in minimum wage requirements, "
        "competition for labor, and unionization efforts could increase "
        "labor costs or disrupt operations, which would adversely affect "
        "our operating margins given the relatively thin margin profile "
        "of our merchandise sales.\n\n"
        "Membership Fee Dependence. A meaningful portion of our operating "
        "income is derived from membership fees. Any deterioration in "
        "membership renewal rates or member acquisition could "
        "disproportionately affect profitability relative to a pure "
        "merchandise-margin retailer."
    ),
    # Page 6 -- MD&A begins
    (
        "Item 7. Management's Discussion and Analysis of Financial "
        "Condition and Results of Operations\n\n"
        "Net sales increased year over year, driven by comparable "
        "warehouse sales growth across most geographic segments and "
        "continued growth in e-commerce. Membership fee income also "
        "increased, reflecting both a membership fee increase and growth "
        "in the total number of paid household members."
    ),
    # Page 7 -- MD&A continued, catalysts-relevant language
    (
        "The Company continues to invest in new warehouse openings, "
        "supply chain modernization including expanded regional "
        "distribution capacity, and technology investments intended to "
        "improve the e-commerce and digital membership experience. "
        "Management believes continued international expansion, "
        "particularly in markets with lower warehouse penetration per "
        "capita, represents a long-term growth opportunity."
    ),
]
